// Human-readable final summary.
// Pulls the key metrics from NanoPlot (read set), QUAST (nuclear assembly), and
// BUSCO (completeness) into one markdown table per sample. Reporting only —
// errorStrategy 'ignore' so a missing/odd input never fails the pipeline.
// Reuses the already-pulled multiqc image (has bash/grep/awk/python).

process FINAL_SUMMARY {
    tag           { sample_id }
    label         'qc'
    errorStrategy 'ignore'
    publishDir    { "${params.outdir}/reports/${sample_id}" }, mode: 'copy'
    container     'quay.io/biocontainers/multiqc:1.25.1--pyhdfd78af_0'

    input:
    tuple val(sample_id), path(nanostats), path(quast_nuclear), path(busco_summary)

    output:
    tuple val(sample_id), path("${sample_id}_assembly_summary.md"), emit: summary

    script:
    """
    #!/usr/bin/env bash
    set -uo pipefail

    NANO="${nanostats}"
    QUAST="${quast_nuclear}/report.tsv"
    BUSCO=\$(ls ${busco_summary} 2>/dev/null | head -1)

    # helper: pull "value" for a leading label from a tab/colon table, else NA
    nano() { grep -iE "^\$1" "\$NANO" 2>/dev/null | head -1 | awk -F'\\t' '{print \$NF}' | tr -d ',' || echo NA; }
    quast() { grep -iE "^\$1" "\$QUAST" 2>/dev/null | head -1 | awk -F'\\t' '{print \$NF}' || echo NA; }

    {
      echo "# Assembly summary — ${sample_id}"
      echo
      echo "_Generated by nf-broom on \$(date -u '+%Y-%m-%d %H:%M UTC')_"
      echo
      echo "## Read set (NanoPlot)"
      echo
      echo "| Metric | Value |"
      echo "|---|---|"
      echo "| Number of reads | \$(nano 'number.of.reads') |"
      echo "| Total bases | \$(nano 'number.of.bases') |"
      echo "| Read N50 | \$(nano 'n50') |"
      echo "| Median read length | \$(nano 'median.read.length') |"
      echo "| Mean read quality | \$(nano 'mean.qual') |"
      echo
      echo "## Nuclear assembly (QUAST)"
      echo
      echo "| Metric | Value |"
      echo "|---|---|"
      echo "| Contigs/scaffolds | \$(quast '# contigs\$') |"
      echo "| Total length | \$(quast 'Total length\$') |"
      echo "| Largest | \$(quast 'Largest contig') |"
      echo "| N50 | \$(quast 'N50') |"
      echo "| GC (%) | \$(quast 'GC') |"
      echo "| N per 100 kbp | \$(quast \"# N's per 100 kbp\") |"
      echo
      echo "## Completeness (BUSCO — ${params.busco_lineage})"
      echo
      echo '```'
      grep -E "C:|Complete|Fragmented|Missing|Total BUSCO" "\$BUSCO" 2>/dev/null | sed 's/^[[:space:]]*//' || echo "NA"
      echo '```'
    } > ${sample_id}_assembly_summary.md
    """
}
