// Human-readable final summary.
// Pulls the key metrics from NanoPlot (read set), QUAST (nuclear assembly), and
// BUSCO (completeness) into one markdown table per sample. Reporting only —
// errorStrategy 'ignore' so a missing/odd input never fails the pipeline.
// Reuses the already-pulled multiqc image (has bash/grep/awk/python).

process FINAL_SUMMARY {
    tag           { sample_id }
    label         'qc'
    errorStrategy 'ignore'
    publishDir    { "${params.outdir}/reports/${sample_id}" }, mode: 'symlink'
    container     'quay.io/biocontainers/multiqc:1.25.1--pyhdfd78af_0'

    input:
    tuple val(sample_id), path(nanostats), path(quast_nuclear), path(busco_summary)

    output:
    tuple val(sample_id), path("${sample_id}_assembly_summary.md"), emit: summary

    script:
    """
    #!/usr/bin/env bash
    set -uo pipefail

    NANO="${nanostats}"
    QUAST="${quast_nuclear}/report.tsv"
    BUSCO=\$(ls ${busco_summary} 2>/dev/null | head -1)

    # NanoPlot: match field name, return last column value
    nano() { awk -F'\\t' -v k="\$1" 'tolower(\$1) ~ tolower(k) {print \$NF; exit}' "\$NANO" 2>/dev/null || echo NA; }

    # QUAST: exact first-column match → print all values as a markdown row
    qrow() {
        awk -F'\\t' -v k="\$1" '
            NR==1 { ncols=NF }
            \$1==k { printf "| **%s** |", \$1; for(i=2;i<=ncols;i++) printf " %s |", \$i; print ""; exit }
        ' "\$QUAST" 2>/dev/null
    }

    # QUAST header row (Assembly names as bold columns)
    qheader() {
        awk -F'\\t' '
            NR==1 { printf "| Metric |"; for(i=2;i<=NF;i++) printf " **%s** |", \$i; print "";
                    printf "|---|";       for(i=2;i<=NF;i++) printf "---|";           print "" }
        ' "\$QUAST" 2>/dev/null
    }

    {
      echo "# Assembly summary — ${sample_id}"
      echo
      echo "_Generated by nf-broom on \$(date -u '+%Y-%m-%d %H:%M UTC')_"
      echo
      echo "## Read set (NanoPlot)"
      echo
      echo "| Metric | Value |"
      echo "|---|---|"
      echo "| Number of reads | \$(nano 'number.of.reads') |"
      echo "| Total bases     | \$(nano 'number.of.bases') |"
      echo "| Read N50        | \$(nano 'n50') |"
      echo "| Median length   | \$(nano 'median.read.length') |"
      echo "| Mean quality    | \$(nano 'mean.qual') |"
      echo
      echo "## Nuclear assembly progression (QUAST)"
      echo
      qheader
      qrow "# contigs"
      qrow "Total length"
      qrow "Largest contig"
      qrow "N50"
      qrow "GC (%)"
      qrow "Genome fraction (%)"
      qrow "# misassemblies"
      qrow "# N's per 100 kbp"
      echo
      echo "## Completeness (BUSCO — ${params.busco_lineage})"
      echo
      echo '```'
      grep -E "C:|Complete|Fragmented|Missing|Total BUSCO" "\$BUSCO" 2>/dev/null | sed 's/^[[:space:]]*//' || echo "NA"
      echo '```'
    } > ${sample_id}_assembly_summary.md
    """
}
